name: Backend Pool Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action (add or remove)'
        required: true
        default: 'add'
      target_group_arn:
        description: 'Target Group ARN'
        required: true
      instance_id:
        description: 'EC2 Instance ID to add/remove'
        required: true
      env:
        description: 'Choose the environment (prod, dev, qa, uat)'
        required: true
        default: 'prod'

jobs:
  manage-backend-pool:
    runs-on: ubuntu-latest
    needs: lb-management  # Ensure LB is created before modifying backend pool
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add or Remove NIC to Target Group
        run: |
          if [ "${{ github.event.inputs.action }}" == "add" ]; then
            aws elbv2 register-targets --target-group-arn ${{ github.event.inputs.target_group_arn }} --targets Id=${{ github.event.inputs.instance_id }} --port 80
          elif [ "${{ github.event.inputs.action }}" == "remove" ]; then
            aws elbv2 deregister-targets --target-group-arn ${{ github.event.inputs.target_group_arn }} --targets Id=${{ github.event.inputs.instance_id }}
          fi
