name: Manage Health Probes

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Add, Update, or Remove Health Probes'
        type: choice
        required: true
        default: 'add'
        options:
          - add
          - update
          - remove
      resource-group:
        description: 'Azure Resource Group'
        required: true
      lb-name:
        description: 'Load Balancer Name'
        required: true
      probe-name:
        description: 'Health Probe Name'
        required: true
      protocol:
        description: 'Protocol (HTTP/TCP)'
        required: true
      port:
        description: 'Port'
        required: true
      interval:
        description: 'Interval (in seconds)'
        required: true
      threshold:
        description: 'Unhealthy Threshold'
        required: true

jobs:
  manage-health-probes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add or Update Health Probe
        if: inputs.action == 'add' || inputs.action == 'update'
        run: |
          az network lb probe create --resource-group ${{ inputs.resource-group }} \
            --lb-name ${{ inputs.lb-name }} --name ${{ inputs.probe-name }} \
            --protocol ${{ inputs.protocol }} --port ${{ inputs.port }} \
            --interval ${{ inputs.interval }} --threshold ${{ inputs.threshold }}

      - name: Remove Health Probe
        if: inputs.action == 'remove'
        run: |
          az network lb probe delete --resource-group ${{ inputs.resource-group }} \
            --lb-name ${{ inputs.lb-name }} --name ${{ inputs.probe-name }}
