name: Health Probe Management

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose action (add or remove)'
        required: true
        default: 'add'
      target_group_arn:
        description: 'Target Group ARN'
        required: true
      env:
        description: 'Choose the environment (prod, dev, qa, uat)'
        required: true
        default: 'prod'

jobs:
  manage-health-probe:
    runs-on: ubuntu-latest
    needs: lb-management  # Ensure LB is created before modifying health probes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add or Remove Health Probe
        run: |
          if [ "${{ github.event.inputs.action }}" == "add" ]; then
            aws elbv2 modify-target-group --target-group-arn ${{ github.event.inputs.target_group_arn }} --health-check-path '/health' --health-check-interval-seconds 30 --health-check-timeout-seconds 5
          elif [ "${{ github.event.inputs.action }}" == "remove" ]; then
            aws elbv2 modify-target-group --target-group-arn ${{ github.event.inputs.target_group_arn }} --health-check-path ''
          fi
