name: VPC and Subnet Setup

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Choose the environment (prod, dev, qa, uat)'
        required: true
        default: 'prod'

jobs:
  create-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Install Terraform using hashicorp/setup-terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.10.2'

      - name: Initialize Terraform
        run: terraform init

      # Use inline variables if terraform.tfvars is missing
      - name: Apply Terraform Configuration
        run: terraform apply -auto-approve -var="env=${{ github.event.inputs.env }}" -var="aws_region=${{ secrets.AWS_REGION }}" -var="subnet_id=${{ secrets.SUBNET_ID }}" -var="vpc_id=${{ secrets.VPC_ID }}"
